//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi41_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int SupplierID { get; set; }
        public string BrandName { get; set; }
        public Nullable<long> Stock { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<int> OneCikanlar { get; set; }
        public Nullable<int> CokSatanlar { get; set; }
        public Nullable<int> BunaBakanlar { get; set; }
        public string Notes { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
